// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20260224031718.migration.dart';
part '20260211025650.migration.dart';
part '20260212070549.migration.dart';
part '20260212075533.migration.dart';
part '20260215050806.migration.dart';
part '20260216050308.migration.dart';
part '20260216050459.migration.dart';
part '20260216070245.migration.dart';
part '20260218143342.migration.dart';
part '20260223183752.migration.dart';
part '20260223201904.migration.dart';
part '20260224040000.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20260224031718(),
  const Migration20260211025650(),
  const Migration20260212070549(),
  const Migration20260212075533(),
  const Migration20260215050806(),
  const Migration20260216050308(),
  const Migration20260216050459(),
  const Migration20260216070245(),
  const Migration20260218143342(),
  const Migration20260223183752(),
  const Migration20260223201904(),
  const Migration20260224040000(),
};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  20260223201904,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'Category',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('slug', Column.varchar),
        SchemaColumn('name_es', Column.varchar),
        SchemaColumn('name_en', Column.varchar),
        SchemaColumn('icon_name', Column.varchar),
        SchemaColumn('sort_order', Column.integer),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Island',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('name_es', Column.varchar),
        SchemaColumn('name_en', Column.varchar),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('area_km2', Column.Double),
        SchemaColumn('area_ha', Column.Double),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
        SchemaColumn('park_id', Column.varchar),
        SchemaColumn('island_type', Column.varchar),
        SchemaColumn('classification', Column.varchar),
        SchemaColumn('is_populated', Column.boolean),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Sighting',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('user_id', Column.varchar),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('visit_site_id', Column.integer),
        SchemaColumn('observed_at', Column.datetime),
        SchemaColumn('notes', Column.varchar),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('photo_url', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Species',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('category_id', Column.integer),
        SchemaColumn('common_name_es', Column.varchar),
        SchemaColumn('common_name_en', Column.varchar),
        SchemaColumn('scientific_name', Column.varchar),
        SchemaColumn('conservation_status', Column.varchar),
        SchemaColumn('weight_kg', Column.Double),
        SchemaColumn('size_cm', Column.Double),
        SchemaColumn('population_estimate', Column.integer),
        SchemaColumn('lifespan_years', Column.integer),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
        SchemaColumn('habitat_es', Column.varchar),
        SchemaColumn('habitat_en', Column.varchar),
        SchemaColumn('hero_image_url', Column.varchar),
        SchemaColumn('thumbnail_url', Column.varchar),
        SchemaColumn('is_endemic', Column.boolean),
        SchemaColumn('taxonomy_kingdom', Column.varchar),
        SchemaColumn('taxonomy_phylum', Column.varchar),
        SchemaColumn('taxonomy_class', Column.varchar),
        SchemaColumn('taxonomy_order', Column.varchar),
        SchemaColumn('taxonomy_family', Column.varchar),
        SchemaColumn('taxonomy_genus', Column.varchar),
        SchemaColumn('is_native', Column.boolean),
        SchemaColumn('is_introduced', Column.boolean),
        SchemaColumn('endemism_level', Column.varchar),
        SchemaColumn('population_trend', Column.varchar),
        SchemaColumn('breeding_season', Column.varchar),
        SchemaColumn('clutch_size', Column.varchar),
        SchemaColumn('reproductive_frequency', Column.varchar),
        SchemaColumn('social_structure', Column.varchar),
        SchemaColumn('activity_pattern', Column.varchar),
        SchemaColumn('diet_type', Column.varchar),
        SchemaColumn('primary_food_sources', Column.varchar),
        SchemaColumn('altitude_min_m', Column.integer),
        SchemaColumn('altitude_max_m', Column.integer),
        SchemaColumn('depth_min_m', Column.integer),
        SchemaColumn('depth_max_m', Column.integer),
        SchemaColumn('scientific_name_authorship', Column.varchar),
        SchemaColumn('distinguishing_features_es', Column.varchar),
        SchemaColumn('distinguishing_features_en', Column.varchar),
        SchemaColumn('sexual_dimorphism', Column.varchar),
        SchemaColumn('gbif_taxon_id', Column.varchar),
        SchemaColumn('eol_page_id', Column.varchar),
        SchemaColumn('iucn_assessment_url', Column.varchar),
        SchemaColumn('sound_recording_url', Column.varchar),
        SchemaColumn('video_url', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'SpeciesImage',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('image_url', Column.varchar),
        SchemaColumn('caption_es', Column.varchar),
        SchemaColumn('caption_en', Column.varchar),
        SchemaColumn('sort_order', Column.integer),
        SchemaColumn('is_primary', Column.boolean),
        SchemaColumn('thumbnail_url', Column.varchar),
        SchemaColumn('card_thumbnail_url', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'SpeciesReference',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('citation', Column.varchar),
        SchemaColumn('url', Column.varchar),
        SchemaColumn('doi', Column.varchar),
        SchemaColumn('reference_type', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'SpeciesSite',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('visit_site_id', Column.integer),
        SchemaColumn('frequency', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'SpeciesSound',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('sound_url', Column.varchar),
        SchemaColumn('sound_type', Column.varchar),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
        SchemaColumn('recorded_by', Column.varchar),
        SchemaColumn('recorded_date', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'SpeciesThreat',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('species_id', Column.integer),
        SchemaColumn('threat_type', Column.varchar),
        SchemaColumn('severity', Column.varchar),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Trail',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer, unique: true),
        SchemaColumn('name_en', Column.varchar),
        SchemaColumn('name_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('island_id', Column.integer),
        SchemaColumn('visit_site_id', Column.integer),
        SchemaColumn('difficulty', Column.varchar),
        SchemaColumn('distance_km', Column.Double),
        SchemaColumn('estimated_minutes', Column.integer),
        SchemaColumn('coordinates', Column.varchar),
        SchemaColumn('elevation_gain_m', Column.Double),
        SchemaColumn('user_id', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'UserFavorite',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('user_id', Column.varchar),
        SchemaColumn('species_id', Column.integer),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'UserProfile',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('display_name', Column.varchar),
        SchemaColumn('bio', Column.varchar),
        SchemaColumn('birth_date', Column.datetime),
        SchemaColumn('country', Column.varchar),
        SchemaColumn('country_code', Column.varchar),
        SchemaColumn('avatar_url', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'VisitSite',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.integer),
        SchemaColumn('island_id', Column.integer),
        SchemaColumn('name_es', Column.varchar),
        SchemaColumn('name_en', Column.varchar),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('description_es', Column.varchar),
        SchemaColumn('description_en', Column.varchar),
        SchemaColumn('monitoring_type', Column.varchar),
        SchemaColumn('difficulty', Column.varchar),
        SchemaColumn('conservation_zone', Column.varchar),
        SchemaColumn('public_use_zone', Column.varchar),
        SchemaColumn('capacity', Column.integer),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('attraction_es', Column.varchar),
        SchemaColumn('abbreviation', Column.varchar),
        SchemaColumn('park_id', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
  },
);
