/// Static list of countries with ISO 3166-1 alpha-2 codes,
/// English names, and Spanish names.
class CountryItem {
  final String code;
  final String nameEn;
  final String nameEs;
  const CountryItem(this.code, this.nameEn, this.nameEs);

  @override
  String toString() => '$code - $nameEn / $nameEs';
}

class Countries {
  Countries._();

  /// All countries sorted alphabetically by English name.
  static const List<CountryItem> all = [
    CountryItem('AF', 'Afghanistan', 'Afganistan'),
    CountryItem('AX', 'Aland Islands', 'Islas Aland'),
    CountryItem('AL', 'Albania', 'Albania'),
    CountryItem('DZ', 'Algeria', 'Argelia'),
    CountryItem('AS', 'American Samoa', 'Samoa Americana'),
    CountryItem('AD', 'Andorra', 'Andorra'),
    CountryItem('AO', 'Angola', 'Angola'),
    CountryItem('AI', 'Anguilla', 'Anguila'),
    CountryItem('AQ', 'Antarctica', 'Antartida'),
    CountryItem('AG', 'Antigua and Barbuda', 'Antigua y Barbuda'),
    CountryItem('AR', 'Argentina', 'Argentina'),
    CountryItem('AM', 'Armenia', 'Armenia'),
    CountryItem('AW', 'Aruba', 'Aruba'),
    CountryItem('AU', 'Australia', 'Australia'),
    CountryItem('AT', 'Austria', 'Austria'),
    CountryItem('AZ', 'Azerbaijan', 'Azerbaiyan'),
    CountryItem('BS', 'Bahamas', 'Bahamas'),
    CountryItem('BH', 'Bahrain', 'Barein'),
    CountryItem('BD', 'Bangladesh', 'Banglades'),
    CountryItem('BB', 'Barbados', 'Barbados'),
    CountryItem('BY', 'Belarus', 'Bielorrusia'),
    CountryItem('BE', 'Belgium', 'Belgica'),
    CountryItem('BZ', 'Belize', 'Belice'),
    CountryItem('BJ', 'Benin', 'Benin'),
    CountryItem('BM', 'Bermuda', 'Bermudas'),
    CountryItem('BT', 'Bhutan', 'Butan'),
    CountryItem('BO', 'Bolivia', 'Bolivia'),
    CountryItem('BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, San Eustaquio y Saba'),
    CountryItem('BA', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'),
    CountryItem('BW', 'Botswana', 'Botsuana'),
    CountryItem('BV', 'Bouvet Island', 'Isla Bouvet'),
    CountryItem('BR', 'Brazil', 'Brasil'),
    CountryItem('IO', 'British Indian Ocean Territory', 'Territorio Britanico del Oceano Indico'),
    CountryItem('BN', 'Brunei Darussalam', 'Brunei'),
    CountryItem('BG', 'Bulgaria', 'Bulgaria'),
    CountryItem('BF', 'Burkina Faso', 'Burkina Faso'),
    CountryItem('BI', 'Burundi', 'Burundi'),
    CountryItem('CV', 'Cabo Verde', 'Cabo Verde'),
    CountryItem('KH', 'Cambodia', 'Camboya'),
    CountryItem('CM', 'Cameroon', 'Camerun'),
    CountryItem('CA', 'Canada', 'Canada'),
    CountryItem('KY', 'Cayman Islands', 'Islas Caiman'),
    CountryItem('CF', 'Central African Republic', 'Republica Centroafricana'),
    CountryItem('TD', 'Chad', 'Chad'),
    CountryItem('CL', 'Chile', 'Chile'),
    CountryItem('CN', 'China', 'China'),
    CountryItem('CX', 'Christmas Island', 'Isla de Navidad'),
    CountryItem('CC', 'Cocos (Keeling) Islands', 'Islas Cocos'),
    CountryItem('CO', 'Colombia', 'Colombia'),
    CountryItem('KM', 'Comoros', 'Comoras'),
    CountryItem('CG', 'Congo', 'Congo'),
    CountryItem('CD', 'Congo, Democratic Republic of the', 'Republica Democratica del Congo'),
    CountryItem('CK', 'Cook Islands', 'Islas Cook'),
    CountryItem('CR', 'Costa Rica', 'Costa Rica'),
    CountryItem('CI', "Cote d'Ivoire", 'Costa de Marfil'),
    CountryItem('HR', 'Croatia', 'Croacia'),
    CountryItem('CU', 'Cuba', 'Cuba'),
    CountryItem('CW', 'Curacao', 'Curazao'),
    CountryItem('CY', 'Cyprus', 'Chipre'),
    CountryItem('CZ', 'Czechia', 'Chequia'),
    CountryItem('DK', 'Denmark', 'Dinamarca'),
    CountryItem('DJ', 'Djibouti', 'Yibuti'),
    CountryItem('DM', 'Dominica', 'Dominica'),
    CountryItem('DO', 'Dominican Republic', 'Republica Dominicana'),
    CountryItem('EC', 'Ecuador', 'Ecuador'),
    CountryItem('EG', 'Egypt', 'Egipto'),
    CountryItem('SV', 'El Salvador', 'El Salvador'),
    CountryItem('GQ', 'Equatorial Guinea', 'Guinea Ecuatorial'),
    CountryItem('ER', 'Eritrea', 'Eritrea'),
    CountryItem('EE', 'Estonia', 'Estonia'),
    CountryItem('SZ', 'Eswatini', 'Esuatini'),
    CountryItem('ET', 'Ethiopia', 'Etiopia'),
    CountryItem('FK', 'Falkland Islands (Malvinas)', 'Islas Malvinas'),
    CountryItem('FO', 'Faroe Islands', 'Islas Feroe'),
    CountryItem('FJ', 'Fiji', 'Fiyi'),
    CountryItem('FI', 'Finland', 'Finlandia'),
    CountryItem('FR', 'France', 'Francia'),
    CountryItem('GF', 'French Guiana', 'Guayana Francesa'),
    CountryItem('PF', 'French Polynesia', 'Polinesia Francesa'),
    CountryItem('TF', 'French Southern Territories', 'Tierras Australes Francesas'),
    CountryItem('GA', 'Gabon', 'Gabon'),
    CountryItem('GM', 'Gambia', 'Gambia'),
    CountryItem('GE', 'Georgia', 'Georgia'),
    CountryItem('DE', 'Germany', 'Alemania'),
    CountryItem('GH', 'Ghana', 'Ghana'),
    CountryItem('GI', 'Gibraltar', 'Gibraltar'),
    CountryItem('GR', 'Greece', 'Grecia'),
    CountryItem('GL', 'Greenland', 'Groenlandia'),
    CountryItem('GD', 'Grenada', 'Granada'),
    CountryItem('GP', 'Guadeloupe', 'Guadalupe'),
    CountryItem('GU', 'Guam', 'Guam'),
    CountryItem('GT', 'Guatemala', 'Guatemala'),
    CountryItem('GG', 'Guernsey', 'Guernsey'),
    CountryItem('GN', 'Guinea', 'Guinea'),
    CountryItem('GW', 'Guinea-Bissau', 'Guinea-Bisau'),
    CountryItem('GY', 'Guyana', 'Guyana'),
    CountryItem('HT', 'Haiti', 'Haiti'),
    CountryItem('HM', 'Heard Island and McDonald Islands', 'Islas Heard y McDonald'),
    CountryItem('VA', 'Holy See', 'Santa Sede'),
    CountryItem('HN', 'Honduras', 'Honduras'),
    CountryItem('HK', 'Hong Kong', 'Hong Kong'),
    CountryItem('HU', 'Hungary', 'Hungria'),
    CountryItem('IS', 'Iceland', 'Islandia'),
    CountryItem('IN', 'India', 'India'),
    CountryItem('ID', 'Indonesia', 'Indonesia'),
    CountryItem('IR', 'Iran, Islamic Republic of', 'Iran'),
    CountryItem('IQ', 'Iraq', 'Irak'),
    CountryItem('IE', 'Ireland', 'Irlanda'),
    CountryItem('IM', 'Isle of Man', 'Isla de Man'),
    CountryItem('IL', 'Israel', 'Israel'),
    CountryItem('IT', 'Italy', 'Italia'),
    CountryItem('JM', 'Jamaica', 'Jamaica'),
    CountryItem('JP', 'Japan', 'Japon'),
    CountryItem('JE', 'Jersey', 'Jersey'),
    CountryItem('JO', 'Jordan', 'Jordania'),
    CountryItem('KZ', 'Kazakhstan', 'Kazajistan'),
    CountryItem('KE', 'Kenya', 'Kenia'),
    CountryItem('KI', 'Kiribati', 'Kiribati'),
    CountryItem('KP', "Korea, Democratic People's Republic of", 'Corea del Norte'),
    CountryItem('KR', 'Korea, Republic of', 'Corea del Sur'),
    CountryItem('KW', 'Kuwait', 'Kuwait'),
    CountryItem('KG', 'Kyrgyzstan', 'Kirguistan'),
    CountryItem('LA', "Lao People's Democratic Republic", 'Laos'),
    CountryItem('LV', 'Latvia', 'Letonia'),
    CountryItem('LB', 'Lebanon', 'Libano'),
    CountryItem('LS', 'Lesotho', 'Lesoto'),
    CountryItem('LR', 'Liberia', 'Liberia'),
    CountryItem('LY', 'Libya', 'Libia'),
    CountryItem('LI', 'Liechtenstein', 'Liechtenstein'),
    CountryItem('LT', 'Lithuania', 'Lituania'),
    CountryItem('LU', 'Luxembourg', 'Luxemburgo'),
    CountryItem('MO', 'Macao', 'Macao'),
    CountryItem('MG', 'Madagascar', 'Madagascar'),
    CountryItem('MW', 'Malawi', 'Malaui'),
    CountryItem('MY', 'Malaysia', 'Malasia'),
    CountryItem('MV', 'Maldives', 'Maldivas'),
    CountryItem('ML', 'Mali', 'Mali'),
    CountryItem('MT', 'Malta', 'Malta'),
    CountryItem('MH', 'Marshall Islands', 'Islas Marshall'),
    CountryItem('MQ', 'Martinique', 'Martinica'),
    CountryItem('MR', 'Mauritania', 'Mauritania'),
    CountryItem('MU', 'Mauritius', 'Mauricio'),
    CountryItem('YT', 'Mayotte', 'Mayotte'),
    CountryItem('MX', 'Mexico', 'Mexico'),
    CountryItem('FM', 'Micronesia, Federated States of', 'Micronesia'),
    CountryItem('MD', 'Moldova, Republic of', 'Moldavia'),
    CountryItem('MC', 'Monaco', 'Monaco'),
    CountryItem('MN', 'Mongolia', 'Mongolia'),
    CountryItem('ME', 'Montenegro', 'Montenegro'),
    CountryItem('MS', 'Montserrat', 'Montserrat'),
    CountryItem('MA', 'Morocco', 'Marruecos'),
    CountryItem('MZ', 'Mozambique', 'Mozambique'),
    CountryItem('MM', 'Myanmar', 'Myanmar'),
    CountryItem('NA', 'Namibia', 'Namibia'),
    CountryItem('NR', 'Nauru', 'Nauru'),
    CountryItem('NP', 'Nepal', 'Nepal'),
    CountryItem('NL', 'Netherlands', 'Paises Bajos'),
    CountryItem('NC', 'New Caledonia', 'Nueva Caledonia'),
    CountryItem('NZ', 'New Zealand', 'Nueva Zelanda'),
    CountryItem('NI', 'Nicaragua', 'Nicaragua'),
    CountryItem('NE', 'Niger', 'Niger'),
    CountryItem('NG', 'Nigeria', 'Nigeria'),
    CountryItem('NU', 'Niue', 'Niue'),
    CountryItem('NF', 'Norfolk Island', 'Isla Norfolk'),
    CountryItem('MK', 'North Macedonia', 'Macedonia del Norte'),
    CountryItem('MP', 'Northern Mariana Islands', 'Islas Marianas del Norte'),
    CountryItem('NO', 'Norway', 'Noruega'),
    CountryItem('OM', 'Oman', 'Oman'),
    CountryItem('PK', 'Pakistan', 'Pakistan'),
    CountryItem('PW', 'Palau', 'Palaos'),
    CountryItem('PS', 'Palestine, State of', 'Palestina'),
    CountryItem('PA', 'Panama', 'Panama'),
    CountryItem('PG', 'Papua New Guinea', 'Papua Nueva Guinea'),
    CountryItem('PY', 'Paraguay', 'Paraguay'),
    CountryItem('PE', 'Peru', 'Peru'),
    CountryItem('PH', 'Philippines', 'Filipinas'),
    CountryItem('PN', 'Pitcairn', 'Islas Pitcairn'),
    CountryItem('PL', 'Poland', 'Polonia'),
    CountryItem('PT', 'Portugal', 'Portugal'),
    CountryItem('PR', 'Puerto Rico', 'Puerto Rico'),
    CountryItem('QA', 'Qatar', 'Catar'),
    CountryItem('RE', 'Reunion', 'Reunion'),
    CountryItem('RO', 'Romania', 'Rumania'),
    CountryItem('RU', 'Russian Federation', 'Rusia'),
    CountryItem('RW', 'Rwanda', 'Ruanda'),
    CountryItem('BL', 'Saint Barthelemy', 'San Bartolome'),
    CountryItem('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Santa Elena, Ascension y Tristan de Acuna'),
    CountryItem('KN', 'Saint Kitts and Nevis', 'San Cristobal y Nieves'),
    CountryItem('LC', 'Saint Lucia', 'Santa Lucia'),
    CountryItem('MF', 'Saint Martin (French part)', 'San Martin (parte francesa)'),
    CountryItem('PM', 'Saint Pierre and Miquelon', 'San Pedro y Miquelon'),
    CountryItem('VC', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas'),
    CountryItem('WS', 'Samoa', 'Samoa'),
    CountryItem('SM', 'San Marino', 'San Marino'),
    CountryItem('ST', 'Sao Tome and Principe', 'Santo Tome y Principe'),
    CountryItem('SA', 'Saudi Arabia', 'Arabia Saudita'),
    CountryItem('SN', 'Senegal', 'Senegal'),
    CountryItem('RS', 'Serbia', 'Serbia'),
    CountryItem('SC', 'Seychelles', 'Seychelles'),
    CountryItem('SL', 'Sierra Leone', 'Sierra Leona'),
    CountryItem('SG', 'Singapore', 'Singapur'),
    CountryItem('SX', 'Sint Maarten (Dutch part)', 'San Martin (parte neerlandesa)'),
    CountryItem('SK', 'Slovakia', 'Eslovaquia'),
    CountryItem('SI', 'Slovenia', 'Eslovenia'),
    CountryItem('SB', 'Solomon Islands', 'Islas Salomon'),
    CountryItem('SO', 'Somalia', 'Somalia'),
    CountryItem('ZA', 'South Africa', 'Sudafrica'),
    CountryItem('GS', 'South Georgia and the South Sandwich Islands', 'Georgia del Sur y las Islas Sandwich del Sur'),
    CountryItem('SS', 'South Sudan', 'Sudan del Sur'),
    CountryItem('ES', 'Spain', 'Espana'),
    CountryItem('LK', 'Sri Lanka', 'Sri Lanka'),
    CountryItem('SD', 'Sudan', 'Sudan'),
    CountryItem('SR', 'Suriname', 'Surinam'),
    CountryItem('SJ', 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen'),
    CountryItem('SE', 'Sweden', 'Suecia'),
    CountryItem('CH', 'Switzerland', 'Suiza'),
    CountryItem('SY', 'Syrian Arab Republic', 'Siria'),
    CountryItem('TW', 'Taiwan, Province of China', 'Taiwan'),
    CountryItem('TJ', 'Tajikistan', 'Tayikistan'),
    CountryItem('TZ', 'Tanzania, United Republic of', 'Tanzania'),
    CountryItem('TH', 'Thailand', 'Tailandia'),
    CountryItem('TL', 'Timor-Leste', 'Timor Oriental'),
    CountryItem('TG', 'Togo', 'Togo'),
    CountryItem('TK', 'Tokelau', 'Tokelau'),
    CountryItem('TO', 'Tonga', 'Tonga'),
    CountryItem('TT', 'Trinidad and Tobago', 'Trinidad y Tobago'),
    CountryItem('TN', 'Tunisia', 'Tunez'),
    CountryItem('TR', 'Turkiye', 'Turquia'),
    CountryItem('TM', 'Turkmenistan', 'Turkmenistan'),
    CountryItem('TC', 'Turks and Caicos Islands', 'Islas Turcas y Caicos'),
    CountryItem('TV', 'Tuvalu', 'Tuvalu'),
    CountryItem('UG', 'Uganda', 'Uganda'),
    CountryItem('UA', 'Ukraine', 'Ucrania'),
    CountryItem('AE', 'United Arab Emirates', 'Emiratos Arabes Unidos'),
    CountryItem('GB', 'United Kingdom', 'Reino Unido'),
    CountryItem('US', 'United States', 'Estados Unidos'),
    CountryItem('UM', 'United States Minor Outlying Islands', 'Islas Menores Exteriores de los Estados Unidos'),
    CountryItem('UY', 'Uruguay', 'Uruguay'),
    CountryItem('UZ', 'Uzbekistan', 'Uzbekistan'),
    CountryItem('VU', 'Vanuatu', 'Vanuatu'),
    CountryItem('VE', 'Venezuela, Bolivarian Republic of', 'Venezuela'),
    CountryItem('VN', 'Viet Nam', 'Vietnam'),
    CountryItem('VG', 'Virgin Islands, British', 'Islas Virgenes Britanicas'),
    CountryItem('VI', 'Virgin Islands, U.S.', 'Islas Virgenes de los Estados Unidos'),
    CountryItem('WF', 'Wallis and Futuna', 'Wallis y Futuna'),
    CountryItem('EH', 'Western Sahara', 'Sahara Occidental'),
    CountryItem('YE', 'Yemen', 'Yemen'),
    CountryItem('ZM', 'Zambia', 'Zambia'),
    CountryItem('ZW', 'Zimbabwe', 'Zimbabue'),
  ];

  /// Find a country by its ISO 3166-1 alpha-2 code.
  static CountryItem? byCode(String code) {
    final upper = code.toUpperCase();
    try {
      return all.firstWhere((c) => c.code == upper);
    } catch (_) {
      return null;
    }
  }

  /// Search countries by name (English or Spanish), case-insensitive.
  static List<CountryItem> search(String query) {
    final lower = query.toLowerCase();
    return all
        .where(
          (c) =>
              c.nameEn.toLowerCase().contains(lower) ||
              c.nameEs.toLowerCase().contains(lower) ||
              c.code.toLowerCase() == lower,
        )
        .toList();
  }
}
